on:
  pull_request:
  push:

jobs:
  version:
    uses: ./.github/workflows/version.yml

  check-rust-version:
    needs: version
    uses: ./.github/workflows/rust-version.yml
    with: 
      version: ${{ needs.version.outputs.tag }}
      cargo_toml_dir: sample_rust
  
  check-kicad-version:
    needs: version
    uses: ./.github/workflows/kicad-version.yml
    with: 
      version: ${{ needs.version.outputs.tag }}
      kicad_sch_path: sample_kicad/sample/sample.kicad_sch

  kicad-release:
    needs: [version, check-kicad-version]
    uses: ./.github/workflows/kicad-release.yml
    with: 
      version: ${{ needs.version.outputs.version }}
      dir: sample_kicad
      name: sample

  docs:
    if: ${{ github.event_name == 'pull_request' || github.ref == 'refs/heads/main' }}
    needs: version
    uses: ./.github/workflows/docs.yml
    with:
      version: ${{ needs.version.outputs.version }}
      pdf-name: "sharedworkflows.pdf"

  deploy:
    # Disable S3 upload: no AWS S3 service available for now
    # TODO: migrate to Google S3
    # if: github.ref == 'refs/heads/main'
    if: false
    needs: [version, docs]
    uses: ./.github/workflows/deploy-s3.yml
    with:
      version: ${{ needs.version.outputs.version }}
      project: shared-workflows
    secrets:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  release:
    if: github.ref == 'refs/heads/main'
    needs: [version, docs]
    uses: ./.github/workflows/deploy-release.yml
    with:
      tag: ${{ needs.version.outputs.tag }}
