on:
  pull_request:
  push:

jobs:
  version:
    uses: noveto-com/shared-workflows/.github/workflows/version.yml@03d4d0e87b81380ceeba1ba5d49b1dd8d61dc87b

  docs:
    if: ${{ github.event_name == 'pull_request' || github.ref == 'refs/heads/main' }}
    needs: version
    uses: noveto-com/shared-workflows/.github/workflows/docs.yml@03d4d0e87b81380ceeba1ba5d49b1dd8d61dc87b
    with:
      version: ${{ needs.version.outputs.version }}
      pdf-name: "sharedworkflows.pdf"

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [version, docs]
    uses: noveto-com/shared-workflows/.github/workflows/deploy-s3.yml@76b5848a444c6839d637ec624360a26adf5640f9
    with:
      version: ${{ needs.version.outputs.version }}
      project: shared-workflows
    secrets:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  release:
    if: github.ref == 'refs/heads/main'
    needs: [version, docs]
    uses: noveto-com/shared-workflows/.github/workflows/deploy-release.yml@c7154fe45d4c2e43cca499a1949d28e222e05865
    with:
      tag: ${{ needs.version.outputs.tag }}
